channels:
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - python
  - pip
  - numpy=1.20
  - cudatoolkit=11.2
  - cudnn=8.1
  - jupyter
  - matplotlib
  - scipy
  - numba
  - joblib
  - scikit-learn
  - scikit-image
  - pandas
  - openpyxl
  - librosa
  - moviepy
  - pip:
    - keras==2.8.0
    - tensorflow==2.8.0
    - tensorflow-io
variables:
  URBANSAS_ROOT: ../urbansas_dataset
  WORKSPACE: ./